Jake logs
bgnerdclub/birb pull request #13
Opened 2023-12-14 21:41 UTC by mavic7

Got module name working. Is not formatted at the moment, just outputs the literal type name, which imo is good enough. Looking for a code review and permission to merge please

2023-12-14 21:42 UTC, mavic7 commented
Also need permission from someone / someone to remove cargo.lock from origin/main and potentially erase history so it does not cause the conflict. cargo.lock has been removed on my end. :)

2023-12-14 21:42 UTC, jw2476 commented
I had a quick look over and it lgtm, I'll review it properly tomorrow

2023-12-15 11:52 UTC, jw2476 requested changes
I like the example and the logging API, nice work on getting the type name out.

I've left a couple minor changes. Also can you run this through `cargo fmt` since some of this isn't formatted correctly

2023-12-15 11:52 UTC, jw2476 commented on .gitignore
> +cargo.lock
I don't know if its case sensitive but should be `Cargo.lock`

2023-12-15 11:52 UTC, jw2476 commented on birb_log/src/lib.rs
> +    pub log_str: String,
I'd rename these to "module", "message" and "log". Also I'd argue that the formatted string shouldn't be stored in the LogEntry and should be formatted when printed.

2023-12-15 11:52 UTC, jw2476 commented on birb_log/src/lib.rs
> +pub type T_Listener = fn(&LogEntry);
Rename to `Listener` to adhere to Rust code style convention

2023-12-15 11:52 UTC, jw2476 commented on birb_log/src/lib.rs
> +        let mut log = Self::default();
Could be a one liner `Self::default()`

2023-12-15 11:52 UTC, jw2476 commented on birb_log/src/lib.rs
> +        return std::any::type_name::<T>().clone().to_string();
Is the double clone nessesary?

2023-12-15 11:52 UTC, jw2476 commented on birb_log/src/lib.rs
> +        for listener in self.listeners.iter() {
you can iterate through a list with:
```rs
for listener in &self.listeners {
```

2023-12-15 11:52 UTC, jw2476 commented on birb_log/src/lib.rs
> +        self.listeners.retain(|x| *x != func);
Has this been tested?

2023-12-15 11:52 UTC, jw2476 commented on birb_log/src/lib.rs
> +            Err(_) => panic!("SystemTime before UNIX EPOCH!")
This could be a call to Result::expect()

2023-12-15 11:52 UTC, jw2476 commented on birb_log/src/lib.rs
> +        let module_name:String = self.translate_mod_uid(object).clone();
This is a triple clone from the original type's string

2023-12-16 18:49 UTC, jw2476 approved these changes
Fantastic work, we'll circle back to this at some point and make some convenient macros but otherwise lgtm.

2023-12-16 19:00 UTC, merged